//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAU_HINH
    {
        public int MA_CAU_HINH { get; set; }
        public int MATB { get; set; }
        public string MAIN { get; set; }
        public Nullable<int> MAN_HINH { get; set; }
        public Nullable<int> CPU { get; set; }
        public Nullable<int> RAM { get; set; }
        public Nullable<int> O_CUNG { get; set; }
        public Nullable<int> VGA { get; set; }
        public Nullable<int> HE_DIEU_HANH { get; set; }
        public string KICH_THUOC { get; set; }
        public string LOAI_MUC { get; set; }
        public string TOC_DO { get; set; }
        public string DO_PHAN_GIAI { get; set; }
        public string CAC_THONG_SO_KHAC { get; set; }
    
        public virtual DM_CPU DM_CPU { get; set; }
        public virtual DM_HDH DM_HDH { get; set; }
        public virtual DM_MAN_HINH DM_MAN_HINH { get; set; }
        public virtual DM_O_CUNG DM_O_CUNG { get; set; }
        public virtual DM_RAM DM_RAM { get; set; }
        public virtual DM_VGA DM_VGA { get; set; }
        public virtual THIETBI THIETBI { get; set; }
    }
}
