//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEU_CHUYEN_THIET_BI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIEU_CHUYEN_THIET_BI()
        {
            this.XAC_NHAN_DIEU_CHUYEN = new HashSet<XAC_NHAN_DIEU_CHUYEN>();
        }
    
        public int MA_DIEU_CHUYEN { get; set; }
        public int MATB { get; set; }
        public string MANS_THEO_DOI { get; set; }
        public Nullable<int> MADV_QL { get; set; }
        public string MANS_QL { get; set; }
        public Nullable<int> MADV_NHAN { get; set; }
        public string MANS_NHAN { get; set; }
        public Nullable<System.DateTime> NGAY_CHUYEN { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual DON_VI DON_VI { get; set; }
        public virtual DON_VI DON_VI1 { get; set; }
        public virtual THIETBI THIETBI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XAC_NHAN_DIEU_CHUYEN> XAC_NHAN_DIEU_CHUYEN { get; set; }
    }
}
