//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_CHUC_NANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_CHUC_NANG()
        {
            this.NHOM_ND_CHUCNANG = new HashSet<NHOM_ND_CHUCNANG>();
        }
    
        public int MA_CHUC_NANG { get; set; }
        public string TEN_CHUC_NANG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHOM_ND_CHUCNANG> NHOM_ND_CHUCNANG { get; set; }
    }
}
