//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINH_ANH
    {
        public int MA_HINH_ANH { get; set; }
        public int MATB { get; set; }
        public string HINH1 { get; set; }
        public string HINH2 { get; set; }
        public string HINH3 { get; set; }
        public string HINH4 { get; set; }
        public string HINH5 { get; set; }
        public string HINH6 { get; set; }
        public string HINH7 { get; set; }
        public string HINH8 { get; set; }
        public string HINH9 { get; set; }
        public string HINH10 { get; set; }
    
        public virtual THIETBI THIETBI { get; set; }
    }
}
