//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOM_ND
    {
        public int MA_NHOM_ND { get; set; }
        public string MA_NHOM { get; set; }
        public string MA_ND { get; set; }
    
        public virtual NGUOI_DUNG NGUOI_DUNG { get; set; }
        public virtual NHOM_NGUOI_DUNG NHOM_NGUOI_DUNG { get; set; }
    }
}
