//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOM_ND_CHUCNANG
    {
        public string MA_NHOM { get; set; }
        public int MA_CHUC_NANG { get; set; }
        public int MA_QUYEN { get; set; }
    
        public virtual DM_CHUC_NANG DM_CHUC_NANG { get; set; }
        public virtual NHOM_NGUOI_DUNG NHOM_NGUOI_DUNG { get; set; }
        public virtual PHAN_QUYEN PHAN_QUYEN { get; set; }
    }
}
