//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyTaiSanCNTTEntities2 : DbContext
    {
        public QuanLyTaiSanCNTTEntities2()
            : base("name=QuanLyTaiSanCNTTEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAU_HINH> CAU_HINH { get; set; }
        public virtual DbSet<DIEU_CHUYEN_THIET_BI> DIEU_CHUYEN_THIET_BI { get; set; }
        public virtual DbSet<DM_CHUC_NANG> DM_CHUC_NANG { get; set; }
        public virtual DbSet<DM_CPU> DM_CPU { get; set; }
        public virtual DbSet<DM_HDH> DM_HDH { get; set; }
        public virtual DbSet<DM_MAN_HINH> DM_MAN_HINH { get; set; }
        public virtual DbSet<DM_O_CUNG> DM_O_CUNG { get; set; }
        public virtual DbSet<DM_RAM> DM_RAM { get; set; }
        public virtual DbSet<DM_VGA> DM_VGA { get; set; }
        public virtual DbSet<DON_VI> DON_VI { get; set; }
        public virtual DbSet<HINH_ANH> HINH_ANH { get; set; }
        public virtual DbSet<LOAI_THIETBI> LOAI_THIETBI { get; set; }
        public virtual DbSet<NGUOI_DUNG> NGUOI_DUNG { get; set; }
        public virtual DbSet<NHA_CUNG_CAP> NHA_CUNG_CAP { get; set; }
        public virtual DbSet<NHAP_KHO> NHAP_KHO { get; set; }
        public virtual DbSet<NHOM_ND> NHOM_ND { get; set; }
        public virtual DbSet<NHOM_NGUOI_DUNG> NHOM_NGUOI_DUNG { get; set; }
        public virtual DbSet<NHOM_THIETBI> NHOM_THIETBI { get; set; }
        public virtual DbSet<PHAN_QUYEN> PHAN_QUYEN { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THIETBI> THIETBIs { get; set; }
        public virtual DbSet<THONG_KE_THIETBI> THONG_KE_THIETBI { get; set; }
        public virtual DbSet<XAC_NHAN_DIEU_CHUYEN> XAC_NHAN_DIEU_CHUYEN { get; set; }
        public virtual DbSet<XUAT_KHO> XUAT_KHO { get; set; }
        public virtual DbSet<NHOM_ND_CHUCNANG> NHOM_ND_CHUCNANG { get; set; }
    }
}
