//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XAC_NHAN_DIEU_CHUYEN
    {
        public int MA_XAC_NHAN { get; set; }
        public Nullable<System.DateTime> THOI_GIAN_XAC_NHAN { get; set; }
        public Nullable<int> MA_DIEU_CHUYEN { get; set; }
        public string MANS_XAC_NHAN { get; set; }
        public string XAC_NHAN { get; set; }
    
        public virtual DIEU_CHUYEN_THIET_BI DIEU_CHUYEN_THIET_BI { get; set; }
    }
}
